// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATGLMRB4SLOeM1WJjWGeGQiqQdBOIkze0',
    appId: '1:722892542420:web:7c2771bfdf5e33db8ac641',
    messagingSenderId: '722892542420',
    projectId: 'aicu-mvp',
    authDomain: 'aicu-mvp.firebaseapp.com',
    storageBucket: 'aicu-mvp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAk_--3EgrRYCyvQuZMhHxQ09gsOJKI8E',
    appId: '1:722892542420:android:8e8503795aa3939e8ac641',
    messagingSenderId: '722892542420',
    projectId: 'aicu-mvp',
    storageBucket: 'aicu-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV_VkoRooMls6NTjAFlzTWgG5u3PEE8ZI',
    appId: '1:722892542420:ios:57321082beb525018ac641',
    messagingSenderId: '722892542420',
    projectId: 'aicu-mvp',
    storageBucket: 'aicu-mvp.firebasestorage.app',
    iosBundleId: 'com.aicu.aicu',
  );
}
